#############################################################################
# Makefile for building: DayLight
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  DayLight.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile DayLight.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -IInclude -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DayLight1.0.0
DISTDIR = /home/shunxu/QtProj/DayLight/.tmp/DayLight1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lglut -lGLU -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		oglwidget.cpp \
		Input/Keyboard.cpp \
		Input/Mouse.cpp \
		Internal/Curve.cpp \
		Internal/Edge.cpp \
		Internal/Ellipsoid.cpp \
		Internal/Face.cpp \
		Internal/Geometry.cpp \
		Internal/Line.cpp \
		Internal/Object.cpp \
		Internal/Shader.cpp \
		Internal/Vector.cpp \
		Output/Cabinet.cpp \
		Output/CVM.cpp \
		Output/OrthoView.cpp \
		Output/TextView.cpp \
		Output/View.cpp \
		Utility/AEL.cpp \
		Utility/Color.cpp \
		Utility/Config.cpp \
		Utility/Matrix.cpp \
		Utility/Utility.cpp \
		Output/WindowManager.cpp moc_mainwindow.cpp \
		moc_View.cpp \
		moc_WindowManager.cpp
OBJECTS       = main.o \
		mainwindow.o \
		oglwidget.o \
		Keyboard.o \
		Mouse.o \
		Curve.o \
		Edge.o \
		Ellipsoid.o \
		Face.o \
		Geometry.o \
		Line.o \
		Object.o \
		Shader.o \
		Vector.o \
		Cabinet.o \
		CVM.o \
		OrthoView.o \
		TextView.o \
		View.o \
		AEL.o \
		Color.o \
		Config.o \
		Matrix.o \
		Utility.o \
		WindowManager.o \
		moc_mainwindow.o \
		moc_View.o \
		moc_WindowManager.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		DayLight.pro mainwindow.h \
		oglwidget.h \
		Include/AEL.h \
		Include/Cabinet.h \
		Include/Color.h \
		Include/Config.h \
		Include/Curve.h \
		Include/CVM.h \
		Include/Edge.h \
		Include/Ellipsoid.h \
		Include/Face.h \
		Include/Geometry.h \
		Include/Index.h \
		Include/Keyboard.h \
		Include/Line.h \
		Include/Matrix.h \
		Include/Mouse.h \
		Include/Object.h \
		Include/OrthoView.h \
		Include/Shader.h \
		Include/TextView.h \
		Include/Utility.h \
		Include/Vector.h \
		Include/View.h \
		Include/WindowManager.h main.cpp \
		mainwindow.cpp \
		oglwidget.cpp \
		Input/Keyboard.cpp \
		Input/Mouse.cpp \
		Internal/Curve.cpp \
		Internal/Edge.cpp \
		Internal/Ellipsoid.cpp \
		Internal/Face.cpp \
		Internal/Geometry.cpp \
		Internal/Line.cpp \
		Internal/Object.cpp \
		Internal/Shader.cpp \
		Internal/Vector.cpp \
		Output/Cabinet.cpp \
		Output/CVM.cpp \
		Output/OrthoView.cpp \
		Output/TextView.cpp \
		Output/View.cpp \
		Utility/AEL.cpp \
		Utility/Color.cpp \
		Utility/Config.cpp \
		Utility/Matrix.cpp \
		Utility/Utility.cpp \
		Output/WindowManager.cpp
QMAKE_TARGET  = DayLight
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = DayLight


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h ui_windowmanager.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DayLight.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		DayLight.pro \
		/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile DayLight.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
DayLight.pro:
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile DayLight.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h oglwidget.h Include/AEL.h Include/Cabinet.h Include/Color.h Include/Config.h Include/Curve.h Include/CVM.h Include/Edge.h Include/Ellipsoid.h Include/Face.h Include/Geometry.h Include/Index.h Include/Keyboard.h Include/Line.h Include/Matrix.h Include/Mouse.h Include/Object.h Include/OrthoView.h Include/Shader.h Include/TextView.h Include/Utility.h Include/Vector.h Include/View.h Include/WindowManager.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp oglwidget.cpp Input/Keyboard.cpp Input/Mouse.cpp Internal/Curve.cpp Internal/Edge.cpp Internal/Ellipsoid.cpp Internal/Face.cpp Internal/Geometry.cpp Internal/Line.cpp Internal/Object.cpp Internal/Shader.cpp Internal/Vector.cpp Output/Cabinet.cpp Output/CVM.cpp Output/OrthoView.cpp Output/TextView.cpp Output/View.cpp Utility/AEL.cpp Utility/Color.cpp Utility/Config.cpp Utility/Matrix.cpp Utility/Utility.cpp Output/WindowManager.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui windowmanager.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_View.cpp moc_WindowManager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_View.cpp moc_WindowManager.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/shunxu/QtProj/DayLight -I/home/shunxu/QtProj/DayLight/Include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_View.cpp: Include/Index.h \
		Include/Vector.h \
		Include/Matrix.h \
		Include/AEL.h \
		Include/View.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/shunxu/QtProj/DayLight -I/home/shunxu/QtProj/DayLight/Include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Include/View.h -o moc_View.cpp

moc_WindowManager.cpp: Include/WindowManager.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/shunxu/QtProj/DayLight -I/home/shunxu/QtProj/DayLight/Include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Include/WindowManager.h -o moc_WindowManager.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_windowmanager.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_windowmanager.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_windowmanager.h: windowmanager.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic windowmanager.ui -o ui_windowmanager.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		Include/Vector.h \
		Include/Index.h \
		Include/Matrix.h \
		Include/WindowManager.h \
		Include/Shader.h \
		Include/Object.h \
		Include/Config.h \
		Include/Color.h \
		Include/Line.h \
		Include/Edge.h \
		Include/Curve.h \
		Include/Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		oglwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

oglwidget.o: oglwidget.cpp oglwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oglwidget.o oglwidget.cpp

Keyboard.o: Input/Keyboard.cpp Include/Keyboard.h \
		Include/Config.h \
		Include/Color.h \
		Include/Index.h \
		Include/Shader.h \
		Include/Object.h \
		Include/Matrix.h \
		Include/Vector.h \
		Include/Line.h \
		Include/Edge.h \
		Include/Geometry.h \
		Include/AEL.h \
		Include/WindowManager.h \
		Include/Utility.h \
		Include/Curve.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Keyboard.o Input/Keyboard.cpp

Mouse.o: Input/Mouse.cpp Include/Mouse.h \
		Include/Vector.h \
		Include/Index.h \
		Include/Matrix.h \
		Include/Config.h \
		Include/Color.h \
		Include/Geometry.h \
		Include/AEL.h \
		Include/Object.h \
		Include/Line.h \
		Include/Shader.h \
		Include/Edge.h \
		Include/WindowManager.h \
		Include/Curve.h \
		Include/Utility.h \
		Include/OrthoView.h \
		Include/View.h \
		Include/Face.h \
		Include/CVM.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mouse.o Input/Mouse.cpp

Curve.o: Internal/Curve.cpp Include/Curve.h \
		Include/Object.h \
		Include/Matrix.h \
		Include/Index.h \
		Include/Config.h \
		Include/Color.h \
		Include/Vector.h \
		Include/Line.h \
		Include/Utility.h \
		Include/WindowManager.h \
		Include/Shader.h \
		Include/Edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Curve.o Internal/Curve.cpp

Edge.o: Internal/Edge.cpp Include/Vector.h \
		Include/Index.h \
		Include/Matrix.h \
		Include/Edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Edge.o Internal/Edge.cpp

Ellipsoid.o: Internal/Ellipsoid.cpp Include/Line.h \
		Include/Vector.h \
		Include/Index.h \
		Include/Matrix.h \
		Include/Ellipsoid.h \
		Include/Object.h \
		Include/Config.h \
		Include/Color.h \
		Include/WindowManager.h \
		Include/Shader.h \
		Include/Edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ellipsoid.o Internal/Ellipsoid.cpp

Face.o: Internal/Face.cpp Include/Vector.h \
		Include/Index.h \
		Include/Matrix.h \
		Include/Face.h \
		Include/Geometry.h \
		Include/AEL.h \
		Include/Object.h \
		Include/Config.h \
		Include/Color.h \
		Include/Line.h \
		Include/Utility.h \
		Include/Shader.h \
		Include/Edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Face.o Internal/Face.cpp

Geometry.o: Internal/Geometry.cpp Include/Geometry.h \
		Include/Vector.h \
		Include/Index.h \
		Include/Matrix.h \
		Include/AEL.h \
		Include/Object.h \
		Include/Config.h \
		Include/Color.h \
		Include/Line.h \
		Include/Shader.h \
		Include/Edge.h \
		Include/WindowManager.h \
		Include/Face.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Geometry.o Internal/Geometry.cpp

Line.o: Internal/Line.cpp Include/Line.h \
		Include/Vector.h \
		Include/Index.h \
		Include/Matrix.h \
		Include/Ellipsoid.h \
		Include/Object.h \
		Include/Config.h \
		Include/Color.h \
		Include/WindowManager.h \
		Include/Shader.h \
		Include/Edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Line.o Internal/Line.cpp

Object.o: Internal/Object.cpp Include/Object.h \
		Include/Matrix.h \
		Include/Index.h \
		Include/Config.h \
		Include/Color.h \
		Include/Vector.h \
		Include/Line.h \
		Include/Face.h \
		Include/Geometry.h \
		Include/AEL.h \
		Include/Edge.h \
		Include/Curve.h \
		Include/Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Object.o Internal/Object.cpp

Shader.o: Internal/Shader.cpp Include/Shader.h \
		Include/Object.h \
		Include/Matrix.h \
		Include/Index.h \
		Include/Config.h \
		Include/Color.h \
		Include/Vector.h \
		Include/Line.h \
		Include/Edge.h \
		Include/OrthoView.h \
		Include/View.h \
		Include/AEL.h \
		Include/Face.h \
		Include/Geometry.h \
		Include/WindowManager.h \
		Include/Utility.h \
		Include/Ellipsoid.h \
		Include/Curve.h \
		Include/CVM.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Shader.o Internal/Shader.cpp

Vector.o: Internal/Vector.cpp Include/Vector.h \
		Include/Index.h \
		Include/Matrix.h \
		Include/OrthoView.h \
		Include/View.h \
		Include/AEL.h \
		Include/Face.h \
		Include/Geometry.h \
		Include/Object.h \
		Include/Config.h \
		Include/Color.h \
		Include/Line.h \
		Include/WindowManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vector.o Internal/Vector.cpp

Cabinet.o: Output/Cabinet.cpp Include/Cabinet.h \
		Include/OrthoView.h \
		Include/Index.h \
		Include/Vector.h \
		Include/Matrix.h \
		Include/View.h \
		Include/AEL.h \
		Include/Face.h \
		Include/Geometry.h \
		Include/Object.h \
		Include/Config.h \
		Include/Color.h \
		Include/Line.h \
		Include/Shader.h \
		Include/Edge.h \
		Include/Mouse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cabinet.o Output/Cabinet.cpp

CVM.o: Output/CVM.cpp Include/View.h \
		Include/Index.h \
		Include/Vector.h \
		Include/Matrix.h \
		Include/AEL.h \
		Include/CVM.h \
		Include/Face.h \
		Include/Geometry.h \
		Include/Object.h \
		Include/Config.h \
		Include/Color.h \
		Include/Line.h \
		Include/Shader.h \
		Include/Edge.h \
		Include/Mouse.h \
		Include/Keyboard.h \
		Include/Curve.h \
		Include/Utility.h \
		Include/WindowManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CVM.o Output/CVM.cpp

OrthoView.o: Output/OrthoView.cpp Include/View.h \
		Include/Index.h \
		Include/Vector.h \
		Include/Matrix.h \
		Include/AEL.h \
		Include/OrthoView.h \
		Include/Face.h \
		Include/Geometry.h \
		Include/Object.h \
		Include/Config.h \
		Include/Color.h \
		Include/Line.h \
		Include/Shader.h \
		Include/Edge.h \
		Include/Mouse.h \
		Include/Keyboard.h \
		Include/Curve.h \
		Include/Utility.h \
		Include/WindowManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OrthoView.o Output/OrthoView.cpp

TextView.o: Output/TextView.cpp Include/TextView.h \
		Include/View.h \
		Include/Index.h \
		Include/Vector.h \
		Include/Matrix.h \
		Include/AEL.h \
		Include/Keyboard.h \
		Include/Config.h \
		Include/Color.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextView.o Output/TextView.cpp

View.o: Output/View.cpp Include/View.h \
		Include/Index.h \
		Include/Vector.h \
		Include/Matrix.h \
		Include/AEL.h \
		Include/OrthoView.h \
		Include/Face.h \
		Include/Geometry.h \
		Include/Object.h \
		Include/Config.h \
		Include/Color.h \
		Include/Line.h \
		Include/Shader.h \
		Include/Edge.h \
		Include/Mouse.h \
		Include/Keyboard.h \
		Include/Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o View.o Output/View.cpp

AEL.o: Utility/AEL.cpp Include/AEL.h \
		Include/Vector.h \
		Include/Index.h \
		Include/Matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AEL.o Utility/AEL.cpp

Color.o: Utility/Color.cpp Include/Color.h \
		Include/Index.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Color.o Utility/Color.cpp

Config.o: Utility/Config.cpp Include/Config.h \
		Include/Color.h \
		Include/Index.h \
		Include/Shader.h \
		Include/Object.h \
		Include/Matrix.h \
		Include/Vector.h \
		Include/Line.h \
		Include/Edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Config.o Utility/Config.cpp

Matrix.o: Utility/Matrix.cpp Include/Matrix.h \
		Include/Index.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Matrix.o Utility/Matrix.cpp

Utility.o: Utility/Utility.cpp Include/AEL.h \
		Include/Vector.h \
		Include/Index.h \
		Include/Matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utility.o Utility/Utility.cpp

WindowManager.o: Output/WindowManager.cpp Include/WindowManager.h \
		Include/Keyboard.h \
		Include/Config.h \
		Include/Color.h \
		Include/Index.h \
		Include/Cabinet.h \
		Include/OrthoView.h \
		Include/Vector.h \
		Include/Matrix.h \
		Include/View.h \
		Include/AEL.h \
		Include/Face.h \
		Include/Geometry.h \
		Include/Object.h \
		Include/Line.h \
		Include/Shader.h \
		Include/Edge.h \
		Include/TextView.h \
		Include/CVM.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WindowManager.o Output/WindowManager.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_View.o: moc_View.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_View.o moc_View.cpp

moc_WindowManager.o: moc_WindowManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WindowManager.o moc_WindowManager.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

